"""empty message

Revision ID: 01c0bca541fe
Revises: 
Create Date: 2023-12-06 01:46:08.208031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c0bca541fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('tel', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=80), nullable=False),
    sa.Column('adm', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_nasc', sa.String(length=80), nullable=False),
    sa.Column('placa_carro', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('estacionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_emp', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('qt_vagas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_emp'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('vaga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estac', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estac'], ['estacionamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vaga', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('dt_inicial', sa.String(length=80), nullable=False),
    sa.Column('dt_final', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vaga.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('vaga')
    op.drop_table('estacionamento')
    op.drop_table('empresa')
    op.drop_table('cliente')
    op.drop_table('user')
    # ### end Alembic commands ###
